version: '3'

services:

  rabbitmq:
    image: rabbitmq:3.11.16-management
    hostname: rabbitmq
    restart: always
    ports:
      - '19722:15672'
    networks:
      - HPDS_197211

  userService:
    build:
      context: ./userService
      dockerfile: Dockerfile
    image: aimadabdelouhab/hpds_197211_userservice:latest
    depends_on:
      - rabbitmq
      - chatapi
    networks:
      - HPDS_197211
    environment:
      - RABBITMQHOST = rabbitmq
      - RABBITMQPORT = 5672
      - RABBITMQUSER = guest
      - RABBITMQPASSWORD = guest
      - DATABASEURL = jdbc:postgresql://actina15.maas:5432/HPDS_197211
      - DATABASEUSER = postgres
      - DATABASEPASSWORD = student

  messageService:
    build:
      context: ./messageService
      dockerfile: Dockerfile
    image: aimadabdelouhab/hpds_197211_messageservice:latest
    depends_on:
      - rabbitmq
      - chatapi
    networks:
      - HPDS_197211
    environment:
      - RABBITMQHOST = rabbitmq
      - RABBITMQPORT = 5672
      - RABBITMQUSER = guest
      - RABBITMQPASSWORD = guest
      - DATABASEURL = jdbc:postgresql://actina15.maas:5432/HPDS_197211
      - DATABASEUSER = postgres
      - DATABASEPASSWORD = student


  chatapi:
    image: aimadabdelouhab/hpds_197211_chatapi:latest
    build:
      context: ./ChatApplicationApi
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - HPDS_197211
    ports:
      - '19721:8090'
    environment:
      - RABBITMQHOST = rabbitmq
      - RABBITMQPORT = 5672
      - RABBITMQUSER = guest
      - RABBITMQPASSWORD = guest

networks:
  HPDS_197211:
    driver: overlay




